[tool.black]
exclude = '.deprecated\/|_example_notebook\/|node_modules\/|__pycache__\/|.pytest_cache\/|.virtual_documents\/|public\/'

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nb2p"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "toml",
    "python-dotenv",
    "loguru",
    'typing_extensions; python_version < "3.11"'
]

[tool.setuptools]
packages = ['nb2p']

[tool.pytest.ini_options]
addopts = [
    "--import-mode=prepend",
]

[tool.isort]
profile = "black"
