// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SessionComponentImport = new FileRoute('/session').createRoute()
const SegmentationComponentImport = new FileRoute('/segmentation').createRoute()
const PipelineViewerComponentImport = new FileRoute(
  '/pipeline-viewer',
).createRoute()
const NotebookComponentImport = new FileRoute('/notebook').createRoute()
const AboutComponentImport = new FileRoute('/about').createRoute()
const IndexComponentImport = new FileRoute('/').createRoute()

// Create/Update Routes

const SessionComponentRoute = SessionComponentImport.update({
  path: '/session',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/session.component'),
    'component',
  ),
})

const SegmentationComponentRoute = SegmentationComponentImport.update({
  path: '/segmentation',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/segmentation.component'),
    'component',
  ),
})

const PipelineViewerComponentRoute = PipelineViewerComponentImport.update({
  path: '/pipeline-viewer',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/pipeline-viewer.component'),
    'component',
  ),
})

const NotebookComponentRoute = NotebookComponentImport.update({
  path: '/notebook',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/notebook.component'),
    'component',
  ),
})

const AboutComponentRoute = AboutComponentImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/about.component'),
    'component',
  ),
})

const IndexComponentRoute = IndexComponentImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutComponentImport
      parentRoute: typeof rootRoute
    }
    '/notebook': {
      preLoaderRoute: typeof NotebookComponentImport
      parentRoute: typeof rootRoute
    }
    '/pipeline-viewer': {
      preLoaderRoute: typeof PipelineViewerComponentImport
      parentRoute: typeof rootRoute
    }
    '/segmentation': {
      preLoaderRoute: typeof SegmentationComponentImport
      parentRoute: typeof rootRoute
    }
    '/session': {
      preLoaderRoute: typeof SessionComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  AboutComponentRoute,
  NotebookComponentRoute,
  PipelineViewerComponentRoute,
  SegmentationComponentRoute,
  SessionComponentRoute,
])
